In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

# Information (raw data)

In [2]:
df = pd.read_csv("../Dataset/acdc_dataset.csv", sep= ';', decimal= ',')

df.head()

,member_id,age,gender,industry,country,is_team_account,n_colleagues_on_account,plan_tier,plan_days_per_week,membership_start,...,uses_event_space,uses_guest_passes,uses_print,uses_mail_handling,uses_phone_booths,uses_day_passes,uses_storage,uses_bike_locker,n_renewals,lifetime_value
0,CW000001,38.0,Female,Information Technology,Portugal,False,0,flex,3,2021-08-01,...,False,True,0,False,True,True,False,False,2,4477.97
1,CW000002,38.0,Male,Information Technology,Portugal,True,2,HOT_DESK,2,2023-11-24,...,False,False,0,True,False,False,False,False,0,165.86
2,CW000003,43.0,Male,Education,DE,True,1,flex,3,2021-12-03,...,False,False,0,False,False,False,False,False,1,4486.17
3,CW000004,38.0,F,Legal,portugal,False,0,flex,3,2022-01-02,...,False,False,0,False,False,False,False,False,0,258.63
4,CW000005,45.0,Female,Information Technology,United Kingdom,False,0,hot_desk,2,2023-10-24,...,False,False,0,False,False,True,False,False,0,335.74

In [3]:
df.shape

(15465, 31)

In [4]:
df.columns

Index(['member_id', 'age', 'gender', 'industry', 'country', 'is_team_account',
       'n_colleagues_on_account', 'plan_tier', 'plan_days_per_week',
       'membership_start', 'membership_end', 'last_badge_swipe',
       'days_since_last_visit', 'total_visits', 'avg_weekly_visits',
       'entitled_visits_last_period', 'actual_visits_last_period',
       'meeting_room_hours', 'event_space_hours', 'guest_passes_issued',
       'uses_meeting_rooms', 'uses_event_space', 'uses_guest_passes',
       'uses_print', 'uses_mail_handling', 'uses_phone_booths',
       'uses_day_passes', 'uses_storage', 'uses_bike_locker', 'n_renewals',
       'lifetime_value'],
      dtype='str')

In [5]:
df.dtypes

member_id                        str
age                              str
gender                           str
industry                         str
country                          str
is_team_account                 bool
n_colleagues_on_account        int64
plan_tier                        str
plan_days_per_week             int64
membership_start                 str
membership_end                   str
last_badge_swipe                 str
days_since_last_visit          int64
total_visits                   int64
avg_weekly_visits                str
entitled_visits_last_period      str
actual_visits_last_period      int64
meeting_room_hours               str
event_space_hours                str
guest_passes_issued              str
uses_meeting_rooms              bool
uses_event_space                bool
uses_guest_passes               bool
uses_print                     int64
uses_mail_handling              bool
uses_phone_booths               bool
uses_day_passes                 bool
uses_storage                    bool
uses_bike_locker                bool
n_renewals                     int64
lifetime_value                   str
dtype: object

In [6]:
df.describe(include='all')

,member_id,age,gender,industry,country,is_team_account,n_colleagues_on_account,plan_tier,plan_days_per_week,membership_start,...,uses_event_space,uses_guest_passes,uses_print,uses_mail_handling,uses_phone_booths,uses_day_passes,uses_storage,uses_bike_locker,n_renewals,lifetime_value
count,15465,14907,14935,15465,15035,15465,15465.000000,15360,15465.000000,15465,...,15465,15465,15465.000000,15465,15465,15465,15465,15465,15465.000000,14425
unique,15450,84,12,43,33,2,NaN,19,NaN,1539,...,2,2,NaN,2,2,2,2,2,NaN,11860
top,CW015101,34.0,Female,Information Technology,Portugal,False,NaN,flex,NaN,2021-01-01,...,False,False,NaN,False,False,False,False,False,NaN,0
freq,2,710,7414,3322,9959,11112,NaN,5182,NaN,560,...,13624,12651,NaN,11901,11469,12069,13169,15439,NaN,1725
mean,NaN,NaN,NaN,NaN,NaN,NaN,0.537019,NaN,3.387262,NaN,...,NaN,NaN,0.323052,NaN,NaN,NaN,NaN,NaN,1.005496,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1.177668,NaN,1.458818,NaN,...,NaN,NaN,0.467658,NaN,NaN,NaN,NaN,NaN,1.353812,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,0.000000,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,-3.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,2.000000,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,3.000000,NaN,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,5.000000,NaN,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,2.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,NaN,9.000000,NaN,...,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,6.000000,NaN

# Duplicates

In [7]:
df.duplicated().sum()

np.int64(15)

In [8]:
df = df.drop_duplicates()
df.shape

(15450, 31)

# Missing Values

In [9]:
df.isna().sum()

member_id                         0
age                             557
gender                          530
industry                          0
country                         429
is_team_account                   0
n_colleagues_on_account           0
plan_tier                       105
plan_days_per_week                0
membership_start                  0
membership_end                    0
last_badge_swipe                  0
days_since_last_visit             0
total_visits                      0
avg_weekly_visits                 0
entitled_visits_last_period       0
actual_visits_last_period         0
meeting_room_hours             1295
event_space_hours                 0
guest_passes_issued            1269
uses_meeting_rooms                0
uses_event_space                  0
uses_guest_passes                 0
uses_print                        0
uses_mail_handling                0
uses_phone_booths                 0
uses_day_passes                   0
uses_storage                      0
uses_bike_locker                  0
n_renewals                        0
lifetime_value                 1040
dtype: int64

In [10]:
nulos = df.isnull().sum()
nulos = nulos[nulos > 0].sort_values(ascending=False)
nulos

meeting_room_hours     1295
guest_passes_issued    1269
lifetime_value         1040
age                     557
gender                  530
country                 429
plan_tier               105
dtype: int64

In [11]:
df.replace("", np.nan, inplace=True)

nulos = df.isnull().sum()
nulos = nulos[nulos > 0].sort_values(ascending=False)
nulos

meeting_room_hours     1295
guest_passes_issued    1269
lifetime_value         1040
age                     557
gender                  530
country                 429
plan_tier               105
dtype: int64

# Cleaning

In [12]:
df.dtypes

member_id                        str
age                              str
gender                           str
industry                         str
country                          str
is_team_account                 bool
n_colleagues_on_account        int64
plan_tier                        str
plan_days_per_week             int64
membership_start                 str
membership_end                   str
last_badge_swipe                 str
days_since_last_visit          int64
total_visits                   int64
avg_weekly_visits                str
entitled_visits_last_period      str
actual_visits_last_period      int64
meeting_room_hours               str
event_space_hours                str
guest_passes_issued              str
uses_meeting_rooms              bool
uses_event_space                bool
uses_guest_passes               bool
uses_print                     int64
uses_mail_handling              bool
uses_phone_booths               bool
uses_day_passes                 bool
uses_storage                    bool
uses_bike_locker                bool
n_renewals                     int64
lifetime_value                   str
dtype: object

### Member_id

In [13]:
df['member_id'].duplicated().sum() #checking for duplicates

np.int64(0)

### Age

In [14]:
df['age'] = df['age'].astype(float) #changing age type

### Gender

In [15]:
df['gender'].unique()

<StringArray>
[ 'Female',    'Male',       'F',   'Other',       nan, ' Female',       'M',
    'male',   ' Male',   'other',  ' Other',  'female',       'O']
Length: 13, dtype: str

In [16]:
gender_dict = {
    "F": "female",
    "M": "male",                #fixing gender labels
    "O": "Other"
               }

df['gender'] = df['gender'].replace(gender_dict)

df['gender'] = df['gender'].str.lower()

df['gender'] = df['gender'].str.strip()

df['gender'].unique()

<StringArray>
['female', 'male', 'other', nan]
Length: 4, dtype: str

### Industry

In [17]:
df['industry'].unique()

<StringArray>
['Information Technology',              'Education',                  'Legal',
                 'Health',                'Unknown',                  'Other',
             'Consulting',      'Design & Creative', 'information technology',
                'Finance',         'Marketing & PR',              'EDUCATION',
      'DESIGN & CREATIVE',       'Marketing and PR',            'Real Estate',
                  'other',             'consulting',         'MARKETING & PR',
 'Information technology',      'design & creative',                  'LEGAL',
         'marketing & pr', 'INFORMATION TECHNOLOGY',                 'health',
           'Marketing/PR',             'CONSULTING',                'unknown',
        'Design/Creative',             'RealEstate',                     'IT',
                   'Tech',         'Marketing & Pr',                  'OTHER',
                  'legal',                'finance',            'real estate',
              'education',    'Design and Creative',                'UNKNOWN',
                'FINANCE',            'REAL ESTATE',                 'HEALTH',
            'Real-Estate']
Length: 43, dtype: str

In [ ]:
industry_dict = {
    "realestate": "real estate",
    "it": "information technology"
}

s = (
    df['industry']
    .str.strip()
    .str.lower()
    .str.replace("/", " & ", regex=False) # "/" -> " & "
    .str.replace(r"\band\b", "&", regex=True) # "and" -> " & "
    .str.replace(r"[-_]", " ", regex=True) # "-" or "_" -> " "
    .str.replace(r"\s*&\s*", " & ", regex=True) # "&" or with more spaces -> " & "
    .str.replace(r"\s+", " ", regex=True) # 1 or more spaces to 1 space
    .str.strip()
)

df['industry'] = s.replace(industry_dict)
df['industry'].unique()

<StringArray>
['information technology',              'education',                  'legal',
                 'health',                'unknown',                  'other',
             'consulting',      'design & creative',                'finance',
         'marketing & pr',            'real estate',                   'tech']
Length: 12, dtype: str

### Country

In [21]:
df['country'].unique()

<StringArray>
[       'Portugal',              'DE',        'portugal',  'United Kingdom',
           'Spain',         'Germany',     'Netherlands',          'France',
              'PT',  'Other (Europe)',        'Portucal',               nan,
              'UK',         'Ireland',  'United kingdom',              'IE',
       'portugal ',     'Deutschland',         'ireland',         'germany',
          'france',  'united kingdom',  'other (europe)',            'U.K.',
              'GB',              'ES',              'NL',          'España',
          'Espana',     'netherlands',           'spain', 'The Netherlands',
              'FR',         'Holland']
Length: 34, dtype: str

In [23]:
country_dict = {
    'portucal' : 'Portugal',
    'portugal ' : 'Portugal',
    'de' : 'Germany',
    'pt' : 'Portugal',
    'deutschland' : 'Germany',
    'uk' : 'United Kingdom',
    'ie' : 'ireland',
    'u.k.' : 'united kingdom',
    'gb' : 'united kingdom',
    'es' : 'spain',
    'españa' : ' spain',
    'espana' : 'spain',
    'fr' : 'france',
    'nl' : 'netherlands',
    'the netherlands' : 'netherlands',
    'holland' : 'netherlands',
}

df['country'] = df['country'].replace(country_dict)

df['country'] = df['country'].str.lower()

df['country'].unique()

<StringArray>
[      'portugal',        'germany', 'united kingdom',          'spain',
    'netherlands',         'france', 'other (europe)',              nan,
        'ireland',         ' spain']
Length: 10, dtype: str

### Is_team_account

In [ ]:
df['is_team_account'].unique() # everything good

array([False,  True])

### Plan_tier

In [24]:
df['plan_tier'].unique()

<StringArray>
[          'flex',       'HOT_DESK',       'hot_desk', 'dedicated_desk',
      'full_time', 'private_office',       'Hot Desk',  'dedicateddesk',
              nan,      'FULL_TIME',        'hotdesk',           'Flex',
           'FLEX',       'fulltime',  'privateoffice',      'Full Time',
 'DEDICATED_DESK', 'Dedicated Desk', 'Private Office', 'PRIVATE_OFFICE']
Length: 20, dtype: str

In [25]:
df['plan_tier'] = df['plan_tier'].str.lower()

df['plan_tier'] = df['plan_tier'].str.replace("_", " ")

plan_tier_dict = {
    "fulltime": "full time",
    "hotdesk": "hot desk",
    "privateoffice": "private office",
    "dedicateddesk": "dedicated desk"
}

df['plan_tier'] = df['plan_tier'].replace(plan_tier_dict)

df['plan_tier'].unique()

<StringArray>
['flex', 'hot desk', 'dedicated desk', 'full time', 'private office', nan]
Length: 6, dtype: str

### Membership_start_end Last_badge_swipe

In [26]:
# trocar dtype para data

### Avg_weekly_visits

In [27]:
df['avg_weekly_visits'] = df['avg_weekly_visits'].astype(float)

### Entitled_visits_last_period

In [29]:
df['entitled_visits_last_period'] = df['entitled_visits_last_period'].astype(float)

### Meeting_room_hours / Event_space_hours / Guest_passes_issued

In [31]:
df['meeting_room_hours'] = df['meeting_room_hours'].astype(float)

df['event_space_hours'] = df['event_space_hours'].astype(float)

df['guest_passes_issued'] = df['guest_passes_issued'].astype(float)

### Uses_print

In [35]:
df['uses_print'].unique()

array([0, 1])

In [36]:
df['uses_print'] = df['uses_print'].astype(bool)

In [38]:
df[['uses_phone_booths', 'uses_day_passes']].dtypes

uses_phone_booths    bool
uses_day_passes      bool
dtype: object

### Lifetime_value

In [ ]:
df['lifetime_value'] = (
    df['lifetime_value']
    .str.replace("€", "", regex=False) # removing "€" and "," to convert to float for metrics
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

# Information (cleaned Data)

In [42]:
df.dtypes

member_id                          str
age                            float64
gender                             str
industry                           str
country                            str
is_team_account                   bool
n_colleagues_on_account          int64
plan_tier                          str
plan_days_per_week               int64
membership_start                   str
membership_end                     str
last_badge_swipe                   str
days_since_last_visit            int64
total_visits                     int64
avg_weekly_visits              float64
entitled_visits_last_period    float64
actual_visits_last_period        int64
meeting_room_hours             float64
event_space_hours              float64
guest_passes_issued            float64
uses_meeting_rooms                bool
uses_event_space                  bool
uses_guest_passes                 bool
uses_print                        bool
uses_mail_handling                bool
uses_phone_booths                 bool
uses_day_passes                   bool
uses_storage                      bool
uses_bike_locker                  bool
n_renewals                       int64
lifetime_value                 float64
dtype: object

In [44]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
member_id,15450,15450,CW000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,14893.0,NaN,NaN,NaN,34.862687,10.39591,1.0,29.0,34.0,40.0,149.0
gender,14920,3,female,7858,NaN,NaN,NaN,NaN,NaN,NaN,NaN
industry,15450,12,information technology,3517,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,15021,9,portugal,10499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_team_account,15450,2,False,11100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
n_colleagues_on_account,15450.0,NaN,NaN,NaN,0.537152,1.177748,-1.0,0.0,0.0,1.0,9.0
plan_tier,15345,5,flex,5449,NaN,NaN,NaN,NaN,NaN,NaN,NaN
plan_days_per_week,15450.0,NaN,NaN,NaN,3.386667,1.458691,0.0,2.0,3.0,5.0,9.0
membership_start,15450,1539,2021-01-01,560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
membership_end,15450,1423,1970-01-01,3954,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last_badge_swipe,15450,1543,2023-12-30,279,NaN,NaN,NaN,NaN,NaN,NaN,NaN
days_since_last_visit,15450.0,NaN,NaN,NaN,117.185631,275.643616,-956.0,4.0,13.0,55.0,1212.0
total_visits,15450.0,NaN,NaN,NaN,110.388285,182.939287,-112.0,8.0,34.0,132.0,6530.0
avg_weekly_visits,15450.0,NaN,NaN,NaN,1.77717,1.937986,0.0,0.71,1.42,2.41,47.4
entitled_visits_last_period,15450.0,NaN,NaN,NaN,27.512777,13.478105,0.0,17.39,26.09,43.48,78.27
actual_visits_last_period,15450.0,NaN,NaN,NaN,13.799159,11.385574,0.0,5.0,10.0,20.0,60.0
meeting_room_hours,14155.0,NaN,NaN,NaN,33.090978,428.349471,-56.6,0.0,0.0,7.2,41220.0
event_space_hours,15450.0,NaN,NaN,NaN,5.116421,26.019696,-13.5,0.0,0.0,0.0,602.8
guest_passes_issued,14181.0,NaN,NaN,NaN,6.160496,23.437578,-24.0,0.0,0.0,0.0,589.0
uses_meeting_rooms,15450,2,False,10192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_event_space,15450,2,False,13612,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_guest_passes,15450,2,False,12639,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_print,15450,2,False,10458,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_mail_handling,15450,2,False,11890,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_phone_booths,15450,2,False,11460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_day_passes,15450,2,False,12056,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_storage,15450,2,False,13157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_bike_locker,15450,2,False,15424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
n_renewals,15450.0,NaN,NaN,NaN,1.005825,1.353727,-3.0,0.0,0.0,2.0,6.0
lifetime_value,14410.0,NaN,NaN,NaN,6398.773732,62789.641423,-13440.24,252.725,825.12,5057.3425,3371260.0